In [18]:
import pathlib
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator

data_dir = pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position')
validation_dir=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position')

image_train= tf.keras.utils.image_dataset_from_directory(
    data_dir,
    labels='inferred',
    label_mode='categorical',
    #class_names=['left', 'no', 'right'],
    color_mode='grayscale',
    batch_size=6,
    image_size=(540,960),
    seed=128,
    validation_split=0.1,
    subset='training',
    )

image_validation= tf.keras.utils.image_dataset_from_directory(
    validation_dir,
    labels='inferred',
    label_mode='categorical',
    #class_names=['left', 'no', 'right'],
    color_mode='grayscale',
    batch_size=6,
    image_size=(540,960),
    seed=128,
    validation_split=0.5,
    subset='validation',
    )


'''
datagen = ImageDataGenerator(rescale=1.0/255)
image_train = datagen.flow_from_directory(
    data_dir,
    target_size=(1080,1920),
    batch_size=6,
    color_mode="grayscale",
    class_mode="sparse",
    shuffle=True,
    subset="training",
    seed=123,
)

vali_datagen = ImageDataGenerator(rescale=1.0/255)

image_validation = vali_datagen.flow_from_directory(
    validation_dir,
    target_size=(1880,1000),
    batch_size=6,
    color_mode="grayscale",
    class_mode="sparse",
    shuffle=False,
    subset="validation",
    seed=123,
)
'''

model = tf.keras.Sequential()
model.add (tf.keras.Input (shape=(540,960)))
#model.add (tf.keras.layers.Reshape ((540,960))) 
model.add (tf.keras.layers.BatchNormalization())
model.add (tf.keras.layers.Bidirectional (tf.keras.layers.GRU (128, return_sequences=True)))
model.add (tf.keras.layers.GRU (64))
model.add (tf.keras.layers.Dense(32,activation='tanh'))
model.add (tf.keras.layers.Dense(12,activation='tanh'))
model.add (tf.keras.layers.Dense(3))

lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    5e-4,
    decay_steps=32,
    decay_rate=0.99,
    staircase=True)

loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True)
opt=tf.keras.optimizers.Adam(learning_rate=lr_schedule)

model.compile (loss=loss, optimizer=opt, metrics=["accuracy"])
model.summary ()

model.fit (image_train, batch_size=12, epochs=10, verbose=2)
model.evaluate (image_validation, batch_size=12, verbose=2)

Found 209 files belonging to 3 classes.
Using 189 files for training.
Found 209 files belonging to 3 classes.
Using 104 files for validation.
Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 batch_normalization_7 (Batc  (None, 540, 960)         3840      
 hNormalization)                                                 
                                                                 
 bidirectional_7 (Bidirectio  (None, 540, 256)         837120    
 nal)                                                            
                                                                 
 gru_15 (GRU)                (None, 64)                61824     
                                                                 
 dense_21 (Dense)            (None, 32)                2080      
                                                                 
 dense_22 (Dense)            (None, 12)     

[0.993588387966156, 0.5480769276618958]

In [19]:
img_0_dir0=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\up\WIN_20220121_18_28_23_Pro.JPG')
img_0_dir1=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\up\WIN_20220121_18_37_10_Pro.JPG')
img_0_dir2=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\up\WIN_20220121_18_39_03_Pro.JPG')
img_0_dir3=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\up\WIN_20220121_18_39_58_Pro.JPG')
img_0_dir4=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\up\WIN_20220121_18_40_27_Pro.JPG')

img_1_dir0=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\center\WIN_20220121_18_30_38_Pro.JPG')
img_1_dir1=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\center\WIN_20220121_18_32_40_Pro.JPG')
img_1_dir2=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\center\WIN_20220121_18_35_38_Pro.JPG')
img_1_dir3=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\center\WIN_20220121_18_38_49_Pro.JPG')
img_1_dir4=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\center\WIN_20220121_18_40_41_Pro.JPG')

img_m1_dir0=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\down\WIN_20220121_18_36_23_Pro.JPG')
img_m1_dir1=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\down\WIN_20220121_18_35_15_Pro.JPG')
img_m1_dir2=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\down\WIN_20220121_18_30_03_Pro.JPG')
img_m1_dir3=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\down\WIN_20220121_18_33_00_Pro.JPG')
img_m1_dir4=pathlib.Path(r'C:\Users\dixon\Desktop\Nanowire_Code\Nanowire_position\down\WIN_20220121_18_40_12_Pro.JPG')

for i in (img_0_dir0,img_0_dir1,img_0_dir2,img_0_dir3,img_0_dir4,
          img_1_dir0,img_1_dir1,img_1_dir2,img_1_dir3,img_1_dir4,
          img_m1_dir0,img_m1_dir1,img_m1_dir2,img_m1_dir3,img_m1_dir4):
    
    image = tf.keras.preprocessing.image.load_img(i,grayscale=True,target_size=(540,960))
    input_arr = tf.keras.preprocessing.image.img_to_array(image)
    input_arr = np.array([input_arr])
    predictions = model.predict(input_arr)
    answer=np.argmax(predictions,axis=1)
    print (predictions, answer)

[[-0.59128815  0.00960791 -0.12993446]] [1]
[[-0.4210131  -0.49286658  0.2040598 ]] [2]
[[-0.41370302 -0.49477535  0.22254549]] [2]
[[-0.30049473 -0.7303457   0.06548206]] [2]
[[ 0.6881267  -0.24693587  0.41608578]] [0]
[[-0.44530183  0.31531563  0.6918345 ]] [2]
[[ 0.43645042  0.6378499  -0.01545942]] [1]
[[-0.46356723 -0.49433097  0.2430958 ]] [2]
[[-0.44813386 -0.52304345  0.26234788]] [2]
[[0.7224622  0.3545647  0.07275634]] [0]
[[-0.44162357 -0.5050041   0.21723498]] [2]
[[-0.47941002 -0.5581458   0.19697495]] [2]
[[0.29879922 0.8807246  0.12582263]] [1]
[[-0.2356354   0.77204853  0.24437259]] [1]
[[ 0.11260494 -0.88386005  0.01559272]] [0]
